import {Router,Request,Response} from 'express';
import jwt from 'jsonwebtoken';
import {User,Organization,Asset,BusinessService,Vulnerability,ThreatActor,Control,InvestmentOption,RiskRun,OptimizationRun,RegulatoryClock,ControlMapping,Framework,AIQuery,Report,AuditEvent,Evidence} from '../models/index.js';
import {config} from '../config/index.js'; import {calculateRisk} from '../engines/risk/riskEngine.js'; import {runScenario} from '../engines/scenario/scenarioEngine.js'; import {optimize} from '../engines/optimization/optimizer.js'; import {complianceOverview} from '../engines/compliance/compliance.js'; import {MockProvider} from '../ai/provider.js'; import {appendAudit,verifyAuditChain} from '../utils/audit.js';
const r=Router();
async function auth(req:Request,res:Response,next:any){const h=req.headers.authorization;if(!h)return res.status(401).json({error:'Authentication required',code:'AUTH_REQUIRED'});try{const d=jwt.verify(h.replace('Bearer ',''),config.jwtSecret) as any;const u=await User.findById(d.userId).select('-password');if(!u)return res.status(401).json({error:'Invalid user',code:'AUTH_INVALID'});(req as any).user=u;next();}catch{return res.status(401).json({error:'Invalid token',code:'AUTH_INVALID'});}}
function out(data:any,provenance:any={}){return {data,meta:{timestamp:new Date().toISOString()},provenance};}
function orgId(req:Request){return (req as any).user.organizationId;}
r.get('/organizations',auth,async(req,res)=>{const o=await Organization.findById(orgId(req));res.json(out(o,{source:'MongoDB'}));});
r.get('/overview',auth,async(req,res)=>{const id=orgId(req);const [risk,assets,vulns,threats,controls,maps,clocks]=await Promise.all([calculateRisk(id),Asset.countDocuments({organizationId:id}),Vulnerability.countDocuments({organizationId:id,status:'OPEN'}),ThreatActor.countDocuments({organizationId:id}),Control.countDocuments({organizationId:id}),ControlMapping.find({organizationId:id,entityType:'University'}),RegulatoryClock.find({organizationId:id})]);res.json(out({risk,counts:{assets,vulnerabilities:vulns,threats,controls},compliance:maps,clocks},{source:'MongoDB+RAVEN engines',model_version:risk.modelVersion,confidence:risk.confidence,freshness:'CACHED/SYNTHETIC'}));});
r.get('/assets',auth,async(req,res)=>res.json(out(await Asset.find({organizationId:orgId(req)}).limit(100))));
r.get('/vulnerabilities',auth,async(req,res)=>res.json(out(await Vulnerability.find({organizationId:orgId(req)}).limit(250))));
r.get('/threats',auth,async(req,res)=>res.json(out(await ThreatActor.find({organizationId:orgId(req)}))));
r.get('/controls',auth,async(req,res)=>res.json(out(await Control.find({organizationId:orgId(req)}))));
r.get('/risk',auth,async(req,res)=>{const x=await calculateRisk(orgId(req));await RiskRun.create({organizationId:orgId(req),riskRunId:`RR-${Date.now()}`,trigger:'DASHBOARD',timestamp:new Date(),modelVersion:x.modelVersion,datasetVersion:x.datasetVersion,seed:x.result.seed,iterations:x.result.iterations,results:x.result,confidence:x.confidence,dataFreshness:'CACHED'});res.json(out(x,{source:'RAVEN risk engine',model_version:x.modelVersion,iterations:x.result.iterations}));});
r.post('/risk/calculate',auth,async(req,res)=>{const iter=Math.min(50000,Math.max(10000,Number(req.body.iterations||10000)));const x=await calculateRisk(orgId(req),iter,Number(req.body.seed||26105));await appendAudit(orgId(req),(req as any).user.email,'risk_run','RiskRun','runtime',{iterations:iter,seed:x.result.seed});res.json(out(x,{source:'Monte Carlo',iterations:iter,seed:x.result.seed}));});
r.post('/scenarios/run',auth,async(req,res)=>{const x=await runScenario(orgId(req),String(req.body.name||'MFA coverage 95%'),(req.body.mutations||{}),10000);await appendAudit(orgId(req),(req as any).user.email,'scenario_run','Scenario','runtime',req.body);res.json(out(x,{source:'Scenario Engine'}));});
r.post('/optimizer/run',auth,async(req,res)=>{const options=await InvestmentOption.find({organizationId:orgId(req)});const budget=Math.max(0,Number(req.body.budget||2500000));const normalized=options.map((o:any)=>({id:o.optionId,name:o.name,cost:o.cost,score:Math.max(0,Math.round((o.effects?.preventive||0)*10000000+(o.effects?.detective||0)*8000000+(o.effects?.response||0)*5000000+(o.effects?.recovery||0)*4000000)),dependencies:o.dependencies||[]}));const sol=optimize(normalized,budget);const baseline=await calculateRisk(orgId(req),10000,26105);const selectedEffects=sol.selected.reduce((a:any,o:any)=>a+(o.score/10000000)*0.02,0);const after=await calculateRisk(orgId(req),10000,26105,sol.selected.reduce((acc:any,o:any)=>{acc[o.id]=(o.score/10000000)*0.02;return acc;},{}));const results={selected:sol.selected,totalCost:sol.cost,budget,ealBefore:baseline.result.eal,ealAfter:after.result.eal,ealReduction:Math.max(0,baseline.result.eal-after.result.eal),varBefore:baseline.result.var95,varAfter:after.result.var95,cvarBefore:baseline.result.cvar95,cvarAfter:after.result.cvar95,rosi:(Math.max(0,baseline.result.eal-after.result.eal)-sol.cost)/Math.max(1,sol.cost),residualEAL:after.result.eal,residualCVaR:after.result.cvar95};const run=await OptimizationRun.create({organizationId:orgId(req),optimizationRunId:`OPT-${Date.now()}`,riskRunId:'runtime',budget,objectiveWeights:req.body.objectiveWeights||{eal:.65,cvar:.2,compliance:.1,strategic:.05},candidateControls:normalized.map(x=>x.id),constraints:{budget},selectedControls:sol.selected.map(x=>x.id),solver:sol.solver,solverStatus:sol.status,results,modelVersion:'RAVEN-CRQ-v1.0',optimizerVersion:'RAVEN-OPT-v1.0',timestamp:new Date()});await appendAudit(orgId(req),(req as any).user.email,'optimizer_run','OptimizationRun',run.optimizationRunId,results);res.json(out({runId:run.optimizationRunId,results},{source:'exact binary optimizer'}));});
r.get('/compliance',auth,async(req,res)=>res.json(out(await complianceOverview(orgId(req),String(req.query.entityType||'University')),{source:'versioned framework registry'})));
r.get('/frameworks',auth,async(req,res)=>res.json(out(await Framework.find({}))));
r.get('/regulatory/clocks',auth,async(req,res)=>res.json(out(await RegulatoryClock.find({organizationId:orgId(req)}))));
r.get('/evidence',auth,async(req,res)=>res.json(out(await Evidence.find({organizationId:orgId(req)}).limit(200))));
r.get('/audit/verify',auth,async(req,res)=>res.json(out(await verifyAuditChain(orgId(req)),{source:'SHA-256 hash chain'})));
r.get('/audit',auth,async(req,res)=>res.json(out(await AuditEvent.find({organizationId:orgId(req)}).sort({timestamp:-1}).limit(100))));
r.post('/ai/ask',auth,async(req,res)=>{const q=String(req.body.question||'');const risk=await calculateRisk(orgId(req));let optimizer={budget:2500000,selected:[]};const provider=new MockProvider();const answer=await provider.answer({question:q,context:{risk,optimizer}});const numericValidated=!/[₹$]\s*[0-9]|\b\d+(?:\.\d+)?%/.test(answer)||answer.includes(new Intl.NumberFormat('en-IN',{maximumFractionDigits:0}).format(Math.round(risk.result.eal)));await AIQuery.create({organizationId:orgId(req),query:q,answer,citations:[{source:'RAVEN risk engine',type:'MODEL_OUTPUT'}],numericValidated,createdAt:new Date()});res.json(out({answer,numericValidated,citations:[{source:'RAVEN risk engine',claimType:'MODEL_DERIVED'}]},{source:'MockProvider',aiBoundary:'explanation-only'}));});
r.get('/reports/board',auth,async(req,res)=>{const id=orgId(req);const [org,risk]=await Promise.all([Organization.findById(id),calculateRisk(id)]);const report={title:'RAVEN Board Report',organization:org?.name,scope:'Synthetic demonstration',generatedAt:new Date().toISOString(),modelVersion:risk.modelVersion,results:risk.result,limitations:['Synthetic enterprise context','Model assumptions are configurable','Not legal/accounting/audit advice']};const rpt=await Report.create({organizationId:id,reportId:`REP-${Date.now()}`,type:'BOARD',modelVersion:risk.modelVersion,optimizationVersion:'RAVEN-OPT-v1.0',dataSnapshot:risk.datasetVersion,generatedAt:new Date(),generatedBy:(req as any).user.email,fileHash:'IN-MEMORY',fileLocation:'JSON response',status:'GENERATED'});res.json(out({...report,reportId:rpt.reportId},{source:'RAVEN report service'}));});
r.get('/reports/board.pdf',auth,async(req,res)=>{const PDF=await import('pdfkit');const id=orgId(req);const risk=await calculateRisk(id);res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename=raven-board-report.pdf');const doc=new PDF.default();doc.pipe(res);doc.fontSize(20).text('RAVEN — BOARD RISK REPORT');doc.moveDown();doc.fontSize(11).text('Synthetic demonstration organization');doc.text(`Generated: ${new Date().toISOString()}`);doc.text(`Model: ${risk.modelVersion} | Dataset: ${risk.datasetVersion}`);doc.moveDown();doc.fontSize(14).text('Financial risk');doc.fontSize(11).text(`EAL: INR ${Math.round(risk.result.eal).toLocaleString('en-IN')}`);doc.text(`VaR95: INR ${Math.round(risk.result.var95).toLocaleString('en-IN')}`);doc.text(`CVaR95: INR ${Math.round(risk.result.cvar95).toLocaleString('en-IN')}`);doc.moveDown();doc.text('Governance: RAVEN estimates economic cyber-risk exposure for decision support and is not legal, accounting, audit or regulatory certification.');doc.end();});
export default r;
