import mongoose, {Schema, Document, Model} from 'mongoose';

const base = {organizationId:{type:Schema.Types.ObjectId, required:true, index:true}};

export type UserRole='EXECUTIVE'|'CISO'|'SECURITY_FINANCE'|'ANALYST'|'AUDITOR'|'REGULATOR'|'SUPER_ADMIN'|'CEO'|'CSFO'|'Executive'|'SuperAdmin';
export interface IUser extends Document {email:string;password:string;name:string;role:UserRole;organizationId?:mongoose.Types.ObjectId;}
const userSchema=new Schema<IUser>({...base,email:{type:String,required:true,unique:true,lowercase:true,trim:true},password:{type:String,required:true,select:true},name:{type:String,required:true},role:{type:String,required:true,enum:['EXECUTIVE','CISO','SECURITY_FINANCE','ANALYST','AUDITOR','REGULATOR','SUPER_ADMIN','CEO','CSFO','Executive','SuperAdmin'],index:true}},{timestamps:true});
import bcrypt from 'bcryptjs';
userSchema.pre('save',async function(next){if(!this.isModified('password'))return next();this.password=await bcrypt.hash(this.password,12);next();});
userSchema.methods.comparePassword=function(candidate:string){return bcrypt.compare(candidate,this.password);};
export const User=mongoose.model<IUser>('User',userSchema);

const organizationSchema=new Schema({...{name:{type:String,required:true},entityType:{type:String,required:true},jurisdiction:{type:String,default:'IN'},regulatedStatus:{type:[String],default:[]},sector:{type:String,default:'Higher Education'},synthetic:{type:Boolean,default:false},labels:{type:[String],default:[]}}},{timestamps:true});
export const Organization=mongoose.model('Organization',organizationSchema);

const assetSchema=new Schema({...base,name:String,type:String,criticality:Number,businessServiceIds:[Schema.Types.ObjectId],internetExposed:Boolean,endpointProtected:Boolean,mfaCoverage:Number,patchDays:Number,piiRecords:Number,sourceType:String,sourceRef:String},{timestamps:true});
export const Asset=mongoose.model('Asset',assetSchema);
const serviceSchema=new Schema({...base,name:String,criticality:Number,hourlyImpact:Number,recoveryHours:Number,pii:Boolean,owner:String},{timestamps:true}); export const BusinessService=mongoose.model('BusinessService',serviceSchema);
const depSchema=new Schema({...base,fromType:String,fromId:Schema.Types.ObjectId,toType:String,toId:Schema.Types.ObjectId,weight:Number},{timestamps:true}); export const Dependency=mongoose.model('Dependency',depSchema);
const vulnSchema=new Schema({...base,cveId:String,assetId:Schema.Types.ObjectId,cvss:Number,epss:Number,kev:Boolean,status:String,source:String,retrievedAt:Date},{timestamps:true}); export const Vulnerability=mongoose.model('Vulnerability',vulnSchema);
const threatSchema=new Schema({...base,name:String,frequencyPerYear:Number,capability:Number,vector:String,sourceType:String},{timestamps:true}); export const ThreatActor=mongoose.model('ThreatActor',threatSchema);
const eventSchema=new Schema({...base,scenarioId:String,assetId:Schema.Types.ObjectId,threatActorId:Schema.Types.ObjectId,frequencyPerYear:Number,status:String,sourceType:String},{timestamps:true}); export const ThreatEvent=mongoose.model('ThreatEvent',eventSchema);
const controlSchema=new Schema({...base,name:String,category:String,cost:Number,annualCost:Number,implementationDays:Number,dependencies:[String],frameworkValues:Schema.Types.Mixed,affectedScenarios:[String],effects:Schema.Types.Mixed,confidence:String,source:String},{timestamps:true}); export const Control=mongoose.model('Control',controlSchema);
const stateSchema=new Schema({...base,controlId:Schema.Types.ObjectId,assetId:Schema.Types.ObjectId,coverage:Number,effectiveness:{preventive:Number,detective:Number,response:Number,recovery:Number},evidenceIds:[Schema.Types.ObjectId],sourceType:String},{timestamps:true}); export const ControlState=mongoose.model('ControlState',stateSchema);
const incidentSchema=new Schema({...base,type:String,occurredAt:Date,loss:Number,sourceType:String,scenarioId:String},{timestamps:true}); export const Incident=mongoose.model('Incident',incidentSchema);
const finSchema=new Schema({...base,name:String,unit:String,value:Number,distribution:{type:String,params:Schema.Types.Mixed},source:String,sourceType:String,basis:String,period:String,confidence:String},{timestamps:true}); export const FinancialAssumption=mongoose.model('FinancialAssumption',finSchema);
const scenarioSchema=new Schema({...base,scenarioId:{type:String,required:true},name:String,description:String,assetId:Schema.Types.ObjectId,businessServiceId:Schema.Types.ObjectId,threatActorId:Schema.Types.ObjectId,vulnerabilityIds:[Schema.Types.ObjectId],controlIds:[Schema.Types.ObjectId],lossComponents:[Schema.Types.Mixed],tef:{type:String,params:Schema.Types.Mixed},susceptibility:{type:String,params:Schema.Types.Mixed},status:String},{timestamps:true}); export const RiskScenario=mongoose.model('RiskScenario',scenarioSchema);
const runSchema=new Schema({...base,riskRunId:String,trigger:String,timestamp:Date,modelVersion:String,datasetVersion:String,seed:Number,iterations:Number,results:Schema.Types.Mixed,confidence:String,dataFreshness:String,inputsHash:String},{timestamps:true}); export const RiskRun=mongoose.model('RiskRun',runSchema);
const contributionSchema=new Schema({...base,riskRunId:String,scenarioId:String,driver:String,assetId:Schema.Types.ObjectId,businessServiceId:Schema.Types.ObjectId,financialContribution:Number,evidenceIds:[Schema.Types.ObjectId],basis:String},{timestamps:true}); export const RiskContribution=mongoose.model('RiskContribution',contributionSchema);
const optionSchema=new Schema({...base,optionId:String,name:String,cost:Number,annualCost:Number,implementationDays:Number,affectedScenarios:[String],effects:Schema.Types.Mixed,dependencies:[String],frameworkValues:Schema.Types.Mixed,confidence:String,source:String},{timestamps:true}); export const InvestmentOption=mongoose.model('InvestmentOption',optionSchema);
const optSchema=new Schema({...base,optimizationRunId:String,riskRunId:String,budget:Number,objectiveWeights:Schema.Types.Mixed,candidateControls:[String],constraints:Schema.Types.Mixed,selectedControls:[String],solver:String,solverStatus:String,results:Schema.Types.Mixed,modelVersion:String,optimizerVersion:String,timestamp:Date},{timestamps:true}); export const OptimizationRun=mongoose.model('OptimizationRun',optSchema);
const mapSchema=new Schema({...base,framework:String,version:String,entityType:String,requirement:String,control:String,evidenceRequired:[String],status:String,sourceUrl:String,sourceType:String,verificationStatus:String,applicabilityRule:String,publicationDate:Date,effectiveDate:Date,supersededDate:Date},{timestamps:true}); export const ControlMapping=mongoose.model('ControlMapping',mapSchema);
const frameworkSchema=new Schema({name:String,version:String,status:String,previousVersion:String,authority:String,sourceUrl:String,sourceType:String,publicationDate:Date,effectiveDate:Date},{timestamps:true}); export const Framework=mongoose.model('Framework',frameworkSchema);
const evidenceSchema=new Schema({...base,evidenceId:String,type:String,description:String,source:String,sourceUrl:String,uploadedBy:String,uploadedAt:Date,hash:String,validFrom:Date,validUntil:Date,applicability:String,framework:String,requirement:String,control:String,status:String},{timestamps:true}); export const Evidence=mongoose.model('Evidence',evidenceSchema);
const clockSchema=new Schema({...base,authority:String,requirement:String,applicability:String,startTime:Date,deadline:Date,evidence:String,owner:String,status:String,source:String,version:String},{timestamps:true}); export const RegulatoryClock=mongoose.model('RegulatoryClock',clockSchema);
const auditSchema=new Schema({...base,auditEventId:String,actor:String,action:String,objectType:String,objectId:String,payload:Schema.Types.Mixed,previousHash:String,payloadHash:String,currentHash:String,timestamp:Date},{timestamps:false}); auditSchema.index({organizationId:1,timestamp:1}); export const AuditEvent=mongoose.model('AuditEvent',auditSchema);
const modelSchema=new Schema({name:String,version:String,description:String,parameters:Schema.Types.Mixed,createdBy:String,approvedAt:Date,status:String},{timestamps:true}); export const ModelVersion=mongoose.model('ModelVersion',modelSchema);
const aiSchema=new Schema({...base,query:String,answer:String,citations:[Schema.Types.Mixed],numericValidated:Boolean,createdAt:Date},{timestamps:false}); export const AIQuery=mongoose.model('AIQuery',aiSchema);
const reportSchema=new Schema({...base,reportId:String,type:String,modelVersion:String,optimizationVersion:String,dataSnapshot:String,generatedAt:Date,generatedBy:String,fileHash:String,fileLocation:String,status:String},{timestamps:true}); export const Report=mongoose.model('Report',reportSchema);
const dsSchema=new Schema({name:String,sourceUrl:String,status:String,retrievedAt:Date,datasetVersion:String,checksum:String,notes:String}); export const DataSource=mongoose.model('DataSource',dsSchema);
const drSchema=new Schema({source:String,datasetVersion:String,retrievedAt:Date,inputHash:String,status:String,recordCount:Number}); export const DataRefresh=mongoose.model('DataRefresh',drSchema);
